services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.24.1
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      # Важно: Мы отключаем встроенные векторизаторы, 
      # так как будем векторизовать через LlamaIndex (локально или API)
      DEFAULT_VECTORIZER_MODULE: 'none' 
      ENABLE_MODULES: 'text2vec-contextionary' # или вообще пусто, если 'none'
      CLUSTER_HOSTNAME: 'node1'
      
volumes:
  weaviate_data: